gpsfun/gpsfun/geokret/urls.py
from django.urls import path
from gpsfun.geokret.views import (
    map_geokret_info, geokrety_map_change_country,
    geokrety_map_search_waypoint, geokrety_map,
    geokrety_api_who_in_cache, geokrety_map_get_geokrety
)

urlpatterns = [
    path('geokret/info/',
        map_geokret_info, name="map-geokret-info"),
    path('change/country/', geokrety_map_change_country,
        name="geokrety-map-change-country"),
    path('search/waypoint/',
        geokrety_map_search_waypoint,
        name="geokret-map-search-by-waypoint"),
    path('map/', geokrety_map, name="geokrety-map"),
    path('cache/<cache_code>/',
        geokrety_api_who_in_cache,
        name="geokrety-api-in-cache"),
    path('get/geokrety/', geokrety_map_get_geokrety,
        name="geokret-map-get-geokrety"),
]

gpsfun/gpsfun/map/urls.py
from django.urls import path
from gpsfun.map.views import (
    map_import_caches_wpt, map_import_caches_wpt_translit,
    map_cache_info, map_rectangle_things, caches_map,
    map_show_types, map_search_waypoint
)

urlpatterns = [
    #path('caches/import/gpx/', map_import_caches_gpx, name="map-import-caches-gpx"),
    path('caches/import/wpt/', map_import_caches_wpt,
        name="map-import-caches-wpt"),
    path('caches/import/wpt/translit/', map_import_caches_wpt_translit,
        name="map-import-caches-wpt-translit"),
    #path('caches/import/kml/$', map_import_caches_kml, name="map-import-caches-kml"),
    path('cache/info/',
        map_cache_info, name="map-cache-info"),
    #path('change/country/', "map_change_country", name="map-change-country"),
    #path('region/caches/', "map_region_caches", name="map-region-caches"),
    #path('confluences/', "map_confluences", name="map-get-confluence"),
    path('things/',
        map_rectangle_things, name="map-get-things"),
    path('map/', caches_map, name="caches-map"),
    path('show/types/',
        map_show_types, name="map-show-types"),
    path('search/waypoint/',
        map_search_waypoint, name="map-search-by-waypoint")
]

gpsfun/gpsfun/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import i18n
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve
from gpsfun.main.views import homepage, update
from gpsfun import geocaching_su_stat


urlpatterns = [
    path('', homepage),
    path('login/', LoginView.as_view(
        template_name='registration/login.html'), name="login"),
    path('logout/', LogoutView.as_view(
        next_page='home'), name='log-out'),
    path('admin/', admin.site.urls),
    path('home/', homepage, name='home'),
    path('update/', update, name='update'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('auth/', include('django.contrib.auth.urls')),
    path('geocaching/su/', include('gpsfun.geocaching_su_stat.urls')),
    path('geocaching/map/', include('gpsfun.map.urls')),
    path('geokrety/map/', include('gpsfun.geokret.urls')),
    path('geokrety/api/', include('gpsfun.geokret.urls')),
    path('user/', include('gpsfun.user.urls')),
    path('geoname/', include('gpsfun.geoname.urls')),
    path('gpsfun-admin/', include('gpsfun.gpsfun_admin.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),

    path('carpathians/routes/', include('gpsfun.carpathians.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gpsfun/gpsfun/user/urls.py
from django.urls import path
from gpsfun.user.views import (user_profile, user_profile_edit)


urlpatterns = [
    path('profile/', user_profile, name="user-profile"),
    path('my/profile/edit/', user_profile_edit,
        name="user-profile-edit"),
]

gpsfun/gpsfun/main/Carpathians/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from gpsfun.utils import get_image_path, media_url, image_url


def thumbnail(width, height):
    MAX = 400
    k = width / height
    if height > MAX:
        height = MAX
        width = int(height * k)
    return {'width': width, 'height': height}


class GeoPoint(models.Model):
    """
    GeoPoint stores data related to point on Earth surface
    """
    latitude = models.DecimalField(
        _("latitude"), default=0, decimal_places=6, max_digits=10)
    longitude = models.DecimalField(
        _("longitude"), default=0, decimal_places=6, max_digits=10)

    def __str__(self):
        return 'point {:10.6f}, {:10.4f}'.format(self.latitude, self.longitude)

    class Meta:
        db_table = 'geopoint'
        verbose_name = _("geopoint")
        verbose_name_plural = _("geopoints")

    def distance_to_point(self, P):
        """
        distance from this point to another point, km
        """
        if P is not None:
            return haversine_distance(
                self.latitude, self.longitude, P.latitude, P.longitude)

    def distance_to_coordinates(self, latitude, longitude):
        """
        distance from this point to point given by coordinates, km
        """
        return haversine_distance(
            self.latitude, self.longitude, latitude, longitude)

    @classmethod
    def degree_from_string(cls, s):
        items = [float(x) for x in s.split()]
        return items[0] + items[1] / 60.0 + items[2] / 3600.0


class Ridge(models.Model):
    slug = models.SlugField(_("slug"), unique=True)
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'ridge'
        verbose_name = _("ridge")
        verbose_name_plural = _("ridges")

    def __str__(self):
        return '%s-%s' % (self.id, self.slug)

    def peaks(self):
        return self.peak_set.order_by('name')

    def routes(self):
        return Route.objects.filter(peak__ridge=self).order_by('number')


class RidgeInfoLink(models.Model):
    ridge = models.ForeignKey(
        Ridge, on_delete=models.PROTECT, verbose_name=_("ridge"))
    link = models.URLField(_("link"), max_length=128)
    description = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        db_table = 'ridge_info_link'
        verbose_name = _("ridge link")
        verbose_name_plural = _("ridge links")

    def __str__(self):
        return '%s-%s' % (self.id, self.link)


class Peak(models.Model):
    slug = models.SlugField(_("slug"), unique=True)
    ridge = models.ForeignKey(
        Ridge, on_delete=models.PROTECT, verbose_name=_("ridge"))
    name = models.CharField(max_length=64, blank=True, null=True)
    height = models.IntegerField(blank=True, null=True, default=0)
    description = models.TextField(blank=True, null=True)
    photo = models.ImageField(
        _("photo"), upload_to=get_image_path, blank=True, null=True)
    point = models.ForeignKey(
        GeoPoint, blank=True, null=True, on_delete=models.SET_NULL,
        verbose_name=_("point"))

    class Meta:
        db_table = 'peak'
        verbose_name = _("peak")
        verbose_name_plural = _("peaks")

    def __str__(self):
        return '%s-%s' % (self.id, self.slug)

    def routes(self):
        return self.route_set.order_by('number')

    def photos(self):
        return self.peakphoto_set.order_by('id')


class PeakPhoto(models.Model):
    peak = models.ForeignKey(
        Peak, on_delete=models.PROTECT, verbose_name=_("peak"))
    photo = models.ImageField(
        _("photo"), upload_to=get_image_path, blank=True, null=True)
    description = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        db_table = 'peak_photo'
        verbose_name = _("peak photo")
        verbose_name_plural = _("peak photos")

    def __str__(self):
        return '%s-%s' % (self.id, self.photo)

    @property
    def thumbnail(self):
        return thumbnail(self.photo.width, self.photo.height)


class Route(models.Model):
    peak = models.ForeignKey(
        Peak, on_delete=models.PROTECT, verbose_name=_("peak"))
    name = models.CharField(max_length=64, blank=True, null=True)
    number = models.PositiveSmallIntegerField(blank=True, null=True)
    short_description = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    photo = models.ImageField(
        _("photo"), upload_to=get_image_path, blank=True, null=True)
    map_image = models.ImageField(
        _("map"), upload_to=get_image_path, blank=True, null=True)
    difficulty = models.CharField(max_length=3, null=True)
    max_difficulty = models.CharField(max_length=16, null=True)
    length = models.IntegerField(blank=True, null=True)
    author = models.CharField(max_length=64, blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    height_difference = models.IntegerField(blank=True, null=True)
    start_height = models.IntegerField(blank=True, null=True)
    descent = models.TextField(blank=True, null=True)
    ready = models.BooleanField(default=False)

    class Meta:
        db_table = 'route'
        verbose_name = _("route")
        verbose_name_plural = _("routes")

    def __str__(self):
        return '%s-%s' % (self.number, self.name)

    def sections(self):
        return self.routesection_set.order_by('num')

    def points(self):
        return self.routepoint_set.order_by('id')

    def photos(self):
        return self.routephoto_set.order_by('id')


class RouteSection(models.Model):
    route = models.ForeignKey(
        Route, on_delete=models.PROTECT, verbose_name=_("route"))
    num = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    length = models.IntegerField(blank=True, null=True)
    angle = models.CharField(max_length=32, blank=True, null=True)
    difficulty = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        db_table = 'route_section'
        verbose_name = _("route section")
        verbose_name_plural = _("route sections")

    def __str__(self):
        return '%s-%s' % (self.id, self.num)

    @property
    def number(self):
        return 'R<sub>{}</sub>-R<sub>{}</sub>'.format(self.num - 1, self.num)

    @property
    def details(self):
        km = self.length // 1000
        m = self.length % 1000
        length = '{}м'.format(m)
        if km:
            length = '{}км '.format(km) + length
        items = [length, ]
        if self.angle:
            items.append(self.angle)
        items.append(self.difficulty)
        return ', '.join(items)


class RoutePhoto(models.Model):
    route = models.ForeignKey(
        Route, on_delete=models.PROTECT, verbose_name=_("route"))
    photo = models.ImageField(
        _("photo"), upload_to=get_image_path, blank=True, null=True)
    description = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        db_table = 'route_photo'
        verbose_name = _("route photo")
        verbose_name_plural = _("route photos")

    def __str__(self):
        return '%s-%s' % (self.id, self.photo)

    @property
    def thumbnail(self):
        return thumbnail(self.photo.width, self.photo.height)


class RoutePoint(models.Model):
    route = models.ForeignKey(
        Route, on_delete=models.PROTECT, verbose_name=_("route"))
    point = models.ForeignKey(
        GeoPoint, blank=True, null=True, on_delete=models.SET_NULL,
        verbose_name=_("point"))
    description = models.CharField(max_length=128, blank=True, null=True)

    class Meta:
        db_table = 'route_point'
        verbose_name = _("route point")
        verbose_name_plural = _("route points")

    def __str__(self):
        return '%s-%s' % (self.route.id, self.point)

gpsfun/gpsfun/DjHDGutils/datatable/controller.py
from copy import deepcopy
from urllib import urlencode,quote,unquote
from django.utils.datastructures import SortedDict
from django.http import Http404,HttpResponse,HttpResponseRedirect,HttpResponseForbidden
from DjHDGutils.paginator import Paginator
from DjHDGutils.datatable.column import Column
from DjHDGutils.datatable.options import Options,Source
from django.template.loader import render_to_string
#from DjHDGutils.datatable.datasource import DataSource
import types

def get_declared_columns(bases, attrs):
    columns = [(column_name, attrs.pop(column_name)) for column_name, obj in attrs.items() if isinstance(obj, Column)]
    columns.sort(lambda x, y: cmp(x[1].creation_counter, y[1].creation_counter))

    for base in bases[::-1]:
        if hasattr(base, 'base_columns'):
            columns = base.base_columns.items() + columns

    return SortedDict(columns)

class ControllerBase(type):
    def __new__(cls, name, bases, attrs):
        columns = get_declared_columns(bases, attrs)
        for col in columns:
            columns[col].name = col
        attrs['base_columns'] = columns

        new_class = type.__new__(cls, name, bases, attrs)

        new_class.add_to_class('_meta', Options(attrs.pop('Meta', None)))

        # Add all attributes to the class.
        for obj_name, obj in attrs.items():
            new_class.add_to_class(obj_name, obj)        

        return new_class

    def add_to_class(cls, name, value):
        if name == 'Source':
            assert type(value) == types.ClassType, "%r attribute of %s model must be a class, not a %s object" % (name, cls.__name__, type(value))
            value = Source(**dict([(k, v) for k, v in value.__dict__.items() if not k.startswith('_')]))

        if hasattr(value, 'contribute_to_class'):
            value.contribute_to_class(cls, name)
        else:
            setattr(cls, name, value)        


class State(object):
    def __init__(self,controller,get_dict):
        self.contoller = controller
        self.state_changed = False
        self.default = True
        self.order_by = controller._meta.ordering

        self._pack_data = None

        if get_dict.get('state',None):
            self.default = False
            self.unpack(get_dict['state'])
            del get_dict['state']

        if get_dict.has_key('order_by'):
            #FIXME check before assign, if column may change ordering
            self.order_by = [get_dict['order_by'],]
            self.state_changed = True
            self.default = False
            del get_dict['order_by']
                

    def unpack(self,state_key):
        state = unquote(state_key)
        state = state.decode('base64_codec')
        lines = state.splitlines()
        if len(lines) > 0:
            self._unpack_order(lines[0])


    def is_changed(self):
        return self.state_changed
        
    def is_default(self):
        return self.default

    def _unpack_order(self,line):
        #FIXME check before assign, if column may change ordering
        self.order_by = line.split(',')

    def _pack_order(self):
        return ",".join(self.order_by)

    def pack(self):
        if self._pack_data:
            return self._pack_data

        self._pack_data = u""
        self._pack_data = self._pack_order()
        self._pack_data += u"\n"

#        print "----------------------"
        self._pack_data = "".join(self._pack_data.encode('base64_codec').splitlines())
#        print self._pack_data
        self._pack_data = 'state=%s'%(quote(self._pack_data))

#        print self._pack_data
        return self._pack_data





class Controller(object):
    __metaclass__ = ControllerBase

    def __init__(self,request):
        self.data_source = None
        self.columns = deepcopy(self.base_columns)
        self.request = request
        self.get_dict = request.GET.copy()
        
        self.state = State(self,self.get_dict)

        self._set_column_order_state()

    def get_column(self,colname):
        return self.columns.get(colname,None)

    def _set_column_order_state(self):
        # set ordering info for columns
        # currently this info used only in template to display order info
        for colname in self.state.order_by:
            desc = False
            if colname[0] == '-':
                colname = colname[1:]
                desc = True
            col = self.get_column(colname)

            if col:
                col.ordered_asc = not desc
                col.ordered_desc = desc

            # IMHO make sence to display order mode only for fist column
            break
                

    def get_redirect(self):
        if self.state.is_changed():
            return HttpResponseRedirect(self.get_start_url())

    def get_data_source(self):
        if self.data_source is None:
            self.data_source = self._meta.data_source.get_source()

        return self.data_source

    def resolve_column_data(self,column,row):
        return self.get_data_source().resolve_column_data(column,row)

    def iter_columns(self):
        for col in self.base_columns:
            yield self.columns[col]

    def get_start_url(self):
        url = '?'
        if len(self.get_dict.items()) > 0:
            url +=  self.get_dict.urlencode()
            url += '&'

        if not self.state.is_default():
            url += self.state.pack()
            url += '&'
            
        return url


    def as_html(self):
        ds = self.get_data_source()
        ds.set_ordering(self.state.order_by)
        
        return render_to_string('datatable.html',
                                { 'controller': self,
                                  'paginator': Paginator(ds,
                                                         self.request.GET.get('page',1),
                                                         self._meta.list_per_page,
                                                         request=self.request) })
    

gpsfun/gpsfun/templates/Map/cache_info.html
{% load i18n %}
<style>
.cach-info-div {
    padding: 5px;
}
</style>
<div class="cach-info-div">
<div><a href="{{ cache.geosite.url }}" target="_blank"><img src="/static/img/{{ cache.geosite.logo }}" alt="{{ cache.site }}" /></a></div>
<b><a href="{{ cache.url }}" target="_blank">{{ cache.code }}</a></b><br/>
<b><a href="{{ cache.url }}" target="_blank">{{ cache.name }}</a></b><br/>
{% trans 'created' %} {{ cache.created_date|date }} {% trans 'by' %} <b>{{ cache.author }}</b> 
</div>

gpsfun/gpsfun/templates/Map/filter_details.html
{% load i18n %}
{% if not controller.search_value %}
<table class="table table-condensed">
{% for item in controller.filter_description %}
<tr>
<td>{{ item.title }}</td>
<td>
{% ifequal item.type "list" %}
{{ item.value|join:"," }}
{% else %}
{{ item.value }}
{% endifequal %}
</td>
</tr>
{% endfor %}
</table>
{% endif %}

gpsfun/gpsfun/templates/Map/geocaching_base.html
{% extends "base_one_column.html" %}
{% load i18n %}


                {% block leftcolumn_content %}
                
                {% endblock %}

gpsfun/gpsfun/templates/Map/geocaching_map.1.html
{% extends "Map/geocaching_map_base.html" %}
{% load i18n %}
{% load static %}

{% block menu_item_map %}active{% endblock %}
{% block in_head %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'js/leaflet/leaflet.css' %}" />
    <script src="{% static 'js/leaflet/leaflet.js' %}"></script>
    <!--meta name="viewport" content="initial-scale=1.0, user-scalable=no" /-->
    <script src="{% static 'jsi18n/' %}" type="text/javascript"></script>
    <!--script src="/r{{ CSSVERSION }}/js/infobubble.js" type="text/javascript"></script-->
    <script src="{% static 'js/browser_kind.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/map.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/leaflet/plugins/Leaflet.MousePosition-master/src/L.Control.MousePosition.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'js/leaflet/plugins/Leaflet.MousePosition-master/src/L.Control.MousePosition.css' %}" />
    <script src="{% static 'js/leaflet/plugins/L.GeoSearch-develop/src/js/l.control.geosearch.js' %}"></script>
    <link rel="stylesheet" href="{% static 'js/leaflet/plugins/L.GeoSearch-develop/src/css/l.geosearch.css' %}" />
    <script src="{% static 'js/leaflet/plugins/L.GeoSearch-develop/src/js/l.geosearch.provider.openstreetmap.js' %}"></script>
    <script src="{% static 'js/leaflet/plugins/leaflet-providers-master/leaflet-providers.js"' %}></script>
    <!--script src="/r{{ CSSVERSION }}/js/leaflet/plugins/PruneCluster-master/dist/PruneCluster.js"></script>
    <link rel="stylesheet" href="/r{{ CSSVERSION }}/js/leaflet/plugins/PruneCluster-master/dist/LeafletStyleSheet.css" /-->
    <!--link rel="stylesheet" href="/r{{ CSSVERSION }}/js/leaflet/plugins/Leaflet.ExtraMarkers-master/dist/css/leaflet.extra-markers.min.css" /-->
    <link rel="stylesheet" href="{% static 'js/leaflet/plugins/BeautifyMarker-master/leaflet-beautify-marker-icon.css' %}" />
    <script src="{% static 'js/leaflet/plugins/BeautifyMarker-master/leaflet-beautify-marker-icon.js' %}"></script>
    <script src="{% static 'js/leaflet/plugins/BeautifyMarker-master/leaflet-beautify-marker.js' %}"></script>



    <script type="text/javascript">
    function initURLs() {
      CachesMap.cache_info_url = '{% url 'map-cache-info' %}';
      CachesMap.get_things_url = '{% url 'map-get-things' %}';
      CachesMap.show_cache_types_url = '{% url 'map-show-types' %}';
    }
    </script>

    <style>
      a.skiplink {
        position: absolute;
        clip: rect(1px, 1px, 1px, 1px);
        padding: 0;
        border: 0;
        height: 1px;
        width: 1px;
        overflow: hidden;
      }
      a.skiplink:focus {
        clip: auto;
        height: auto;
        width: auto;
        background-color: #fff;
        padding: 0.3em;
      }
      #map:focus {
        outline: #4A74A8 solid 0.15em;
      }
    </style>
    <script>
        //ACCESS_TOKEN = 'pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpandmbXliNDBjZWd2M2x6bDk3c2ZtOTkifQ._QA7i5Mpkd_m30IGElHziw';
        //MB_ATTR = 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
        //    '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
        //    'Imagery © <a href="http://mapbox.com">Mapbox</a>';
        //MB_URL = 'https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=' + ACCESS_TOKEN;
        //OSM_URL = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
        //OSM_ATTRIB = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors';
    </script>
{% endblock %}

{% block body_onload %}{% endblock %}

{% block main-content %}
<a class="skiplink" href="#map">Go to map</a>
<div class="container">
<div id="map" class="map map-home" style="height: 450px; margin-top: 50px"></div>
</div>

    <script>
        initURLs();
        CachesMap.init([{{ map_center.lat }}, {{ map_center.lon }}], {{ map_zoom }});
    </script>

<div class="panel panel-default">
  <div class="panel-body">

      <!-- Button trigger modal -->
      <a data-toggle="modal" href="#myModal" class="btn btn-default">{% trans "Filter" %}</a>
      <!--div class="" id="id_current_location"></div-->

    <form id="form_1" class="form-inline pull-right" action="">
      <span class="" id="id_count">{% if caches_count %}{% trans "found" %}: {{ caches_count|default_if_none:""}}{% endif %}</span>

      <span class="" id="import_data" style="display:{% if caches.count %}inline{% else %}none{% endif %}">
    <!--a class="btn btn-default" href="{% url 'map-import-caches-wpt' %}">WPT</a>
    <a class="btn btn-default" href="{% url 'map-import-caches-wpt-translit' %}">WPT translit</a-->
      </span>
    </form>
    <span id="map_spinner" style="display:none"><img src="{% static 'img/spinner-bar.gif' %}" /></span>
  </div>
  <div >
  <table>
    <tr><td id="toomanycaches_txt"></td></tr>
  </table>
</div>
</div>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Show caches</h4>
        </div>
        <div class="modal-body">
          <div class="checkbox">
          <form class="form-horizontal" role="form" action="" id="id_form_types">
          {% for type in cache_types %}
            <div class="checkbox">
            <label>
              <input type="checkbox" name="hidden_caches[]" value="{{ type.code }}"
                  {% if type.code in user_types %}checked{% endif %}
                  onChange="CachesMap.showCacheTypes(this);" />
                  {{ type.name }}
            </label>
            </div>
          {% endfor %}
          </form>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->


{% endblock %}

gpsfun/gpsfun/templates/Map/geocaching_map_base.html
{% extends "base_bootstrap.html" %}
{% load i18n %}
{% block main_div_class %}
    <div class="container-fluid">
{% endblock %}

{% block content %}
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="col-md-12">
          {% block main-content %}
          {% endblock %}
        </div>
      </div>
    </div>
{% endblock %}

{% block footer-class %}container{% endblock %}

gpsfun/gpsfun/templates/Map/geokret_info.html
{% load i18n %}
<style>
  .cach-info-div {
    padding: 5px;
}
</style>

<div class="geokret-info-div">
  <div>
    <a href="{{ waypoint_url }}" target="_blank">
      <span class="infofont">{% trans "Cache" %}: {{ kret_point.waypoint }}</span>
    </a>
  </div>
  <br/><br/>
  {% for geokret in krety %}
    <a href="{{ geokret.url }}" target="_blank">
      <span class="infofont">{{ geokret.reference_number }}</span>
    </a>
    <span class="infofont">{{ geokret.distance }}{% trans "km" %} </span>
    <b>{{ geokret.name }}</b>
  {% endfor %}
</div>

gpsfun/gpsfun/templates/Map/location_widget.html
{% load i18n %}

{% block main-content %}
<div id="map_canvas" style="width:400px; height:300px;"></div>
<br>


<div id="id_latitude_block" class="control-group">
 <div class="input-group">
  <input type="hidden" name="lat_sign" value="N" id="id_lat_sign">
  <button class="btn btn-default" type="button" id="btn_lat_sign">N</button>
  <input class="input-midi" id="id_latitude" type="text" name="latitude" value="" style="font-size:18px;" />
 </div>
</div>

<div id="id_longitude_block" class="control-group">
 <div class="input-group warning">
  <input type="hidden" name="lon_sign" value="E" id="id_lon_sign">
  <button class="btn btn-default" type="button" id="btn_lon_sign">E</button>
  <input class="input-midi" id="id_longitude" type="text" name="longitude" value=""  style="font-size:18px;"/>
 </div>
 </div>

<script>
var panel= $("#id_latitude_block");
panel.find("input:text").blur(function(){SetPosition.validate(this);});
panel.find("button").click(function(){SetPosition.toggleSign(this);});

var panel= $("#id_longitude_block");
panel.find("input:text").blur(function(){SetPosition.validate(this);});
panel.find("button").click(function(){SetPosition.toggleSign(this);});

</script>
{% endblock %}